- image_filepath: data/cropped/images/fsm042.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm042.dc.norev.mgz
- image_filepath: data/cropped/images/fsm020.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm020.dc.norev.mgz
- image_filepath: data/cropped/images/fsm039.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm039.dc.norev.mgz
- image_filepath: data/cropped/images/fsm007.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm007.dc.norev.mgz
- image_filepath: data/cropped/images/fsm012.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm012.dc.norev.mgz
- image_filepath: data/cropped/images/fsm028.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm028.dc.norev.mgz
- image_filepath: data/cropped/images/fsm029.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm029.dc.norev.mgz
- image_filepath: data/cropped/images/fsm026.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm026.dc.norev.mgz
- image_filepath: data/cropped/images/fsm036.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm036.dc.norev.mgz
- image_filepath: data/cropped/images/fsm033.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm033.dc.norev.mgz
- image_filepath: data/cropped/images/fsm019.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm019.dc.norev.mgz
- image_filepath: data/cropped/images/fsm009.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm009.dc.norev.mgz
- image_filepath: data/cropped/images/fsm038.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm038.dc.norev.mgz
- image_filepath: data/cropped/images/fsm021.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm021.dc.norev.mgz
- image_filepath: data/cropped/images/fsm004.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm004.dc.norev.mgz
- image_filepath: data/cropped/images/fsm011.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm011.dc.norev.mgz
- image_filepath: data/cropped/images/fsm008.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm008.dc.norev.mgz
- image_filepath: data/cropped/images/fsm027.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm027.dc.norev.mgz
- image_filepath: data/cropped/images/fsm013.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm013.dc.norev.mgz
- image_filepath: data/cropped/images/fsm010.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm010.dc.norev.mgz
- image_filepath: data/cropped/images/fsm041.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm041.dc.norev.mgz
- image_filepath: data/cropped/images/fsm035.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm035.dc.norev.mgz
- image_filepath: data/cropped/images/fsm031.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm031.dc.norev.mgz
- image_filepath: data/cropped/images/fsm017.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm017.dc.norev.mgz
- image_filepath: data/cropped/images/fsm014.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm014.dc.norev.mgz
- image_filepath: data/cropped/images/fsm023.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm023.dc.norev.mgz
- image_filepath: data/cropped/images/fsm025.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm025.dc.norev.mgz
- image_filepath: data/cropped/images/fsm015.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm015.dc.norev.mgz
- image_filepath: data/cropped/images/fsm006.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm006.dc.norev.mgz
- image_filepath: data/cropped/images/fsm022.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm022.dc.norev.mgz
- image_filepath: data/cropped/images/fsm018.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm018.dc.norev.mgz
- image_filepath: data/cropped/images/fsm005.dc.norev.mgz
  label_filepath: data/cropped/labels/fsm005.dc.norev.mgz
